---

- hosts: all
  become: true
  tasks: 

  - name: apt update
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: pacman update
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"

  - name: apt install apache2, htop, git, neofetch
    apt:
      name:
        - apache2
        - htop
        - git
        - neofetch
    when: ansible_distribution in ["Ubuntu", "Debian"]

  - name: pacman install apache, htop, git, neofetch
    pacman:
      name: 
        - apache
        - htop
        - git
        - neofetch
    when: ansible_distribution == "Archlinux"
