---

- hosts: all
  become: true
  tasks: 

  - name: apt update
    apt:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Ubuntu" and "Debian"

  - name: pacman update
    pacman:
      update_cache: yes
      upgrade: yes
    when: ansible_distribution == "Archlinux"

  - name: apt install apache2, htop
    apt:
      name: apache2
      name: htop
    when: ansible_distribution == "Ubuntu" and "Debian"

  - name: pacman install apache, htop, neofetch
    pacman:
      name: apache
      name: htop
      name: neofetch
    when: ansible_distribution == "Archlinux"
