---

- hosts: sonarr # insert hostname 
  become: false
  become_user: root
  become_method: su
  tasks: 

    #  - name: Initialize pacman keyring (Arch Linux)
    #    when: ansible_distribution == 'Archlinux'
    #    become: true
    #    ansible.builtin.shell: pacman-key --init

    #  - name: Populate pacman keyring (Arch Linux)
    #    when: ansible_distribution == 'Archlinux'
    #    become: true
    #    ansible.builtin.shell: pacman-key --populate

    #  - name: Refresh pacman keys (Arch Linux)
    #    when: ansible_distribution == 'Archlinux'
    #    become: true
    #    ansible.builtin.shell: pacman-key --refresh-keys

  - name: update & upgrade
    package:
      update_cache: yes
      upgrade: yes

  - name: update & package install
    package:
      name:
        - vim
        - sudo
        - python3
        - git
        - htop
        - rsync
        - neofetch
        - curl
        - wget
        - unzip
        - zip
        - tar
      state: latest
